# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('money', models.IntegerField(default=20000, validators=[django.core.validators.MaxValueValidator(80000), django.core.validators.MinValueValidator(20000)])),
                ('title', models.CharField(max_length=32)),
                ('type', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.IntegerField(default=0)),
                ('last', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studsem_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_acy', models.IntegerField()),
                ('sts_sem', models.IntegerField()),
                ('std_serno', models.CharField(max_length=64)),
                ('cls_id', models.CharField(max_length=16)),
                ('cls_name', models.CharField(max_length=20)),
                ('sec_name', models.CharField(max_length=10)),
                ('sub_name', models.CharField(max_length=10)),
                ('sub_name2', models.CharField(max_length=10)),
                ('col_fname', models.CharField(max_length=16)),
                ('dep_no', models.CharField(max_length=6)),
                ('dep_fname', models.CharField(max_length=16)),
                ('cls_year', models.IntegerField()),
                ('cls_class', models.CharField(max_length=1)),
                ('sts_status', models.IntegerField()),
                ('msg_name', models.CharField(max_length=32)),
                ('sts_ptpone', models.CharField(max_length=1)),
                ('sts_back', models.CharField(max_length=1)),
                ('sts_tsch', models.CharField(max_length=1)),
                ('sts_tdep', models.CharField(max_length=1)),
                ('sts_five', models.CharField(max_length=1)),
                ('std_sex', models.CharField(max_length=1)),
                ('esc_code', models.CharField(blank=True, max_length=16)),
                ('esc_name', models.CharField(blank=True, max_length=16)),
                ('eqa_code', models.CharField(max_length=8)),
                ('eqa_name', models.CharField(max_length=16)),
                ('eid_code', models.CharField(max_length=8)),
                ('eid_name', models.CharField(max_length=24)),
                ('eid_code_a', models.CharField(max_length=8)),
                ('eid_name2', models.CharField(max_length=24)),
                ('sch_code', models.CharField(max_length=16)),
                ('sch_fname', models.CharField(max_length=32)),
                ('sdp_code', models.CharField(blank=True, max_length=32)),
                ('sdp_name', models.CharField(blank=True, max_length=32)),
                ('prv_code_n', models.CharField(blank=True, max_length=16)),
                ('prv_name', models.CharField(blank=True, max_length=16)),
                ('abg_code', models.CharField(blank=True, max_length=32)),
                ('abg_name', models.CharField(blank=True, max_length=32)),
                ('zip_name1', models.CharField(max_length=16)),
                ('zip_name2', models.CharField(max_length=16)),
                ('std_entym', models.CharField(max_length=16)),
                ('hst_type', models.CharField(blank=True, max_length=16)),
                ('hst_acy', models.CharField(blank=True, max_length=16)),
                ('hst_sem', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rate', models.FloatField(default=0.0)),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.SchoolData'),
        ),
    ]
