# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='dirName',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
