# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-03 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acy', models.IntegerField()),
                ('dep_no', models.CharField(max_length=20)),
                ('cas_key', models.CharField(max_length=20)),
                ('pef_key', models.CharField(max_length=20)),
                ('pep_key', models.CharField(max_length=20)),
                ('cas_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dep2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acy', models.IntegerField()),
                ('dep_no', models.CharField(max_length=20)),
                ('col_no', models.CharField(max_length=20)),
                ('dep_sname', models.CharField(max_length=32)),
                ('dep_fname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Studsem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_acy', models.IntegerField()),
                ('sts_sem', models.IntegerField()),
                ('std_serno', models.CharField(max_length=20)),
                ('cls_id', models.CharField(max_length=20)),
                ('sts_status', models.IntegerField()),
                ('sts_reason', models.IntegerField(blank=True)),
                ('sts_ptpone', models.BooleanField()),
                ('sts_back', models.BooleanField()),
                ('sts_tsch', models.BooleanField()),
                ('sts_tdep', models.BooleanField()),
                ('sts_five', models.BooleanField()),
            ],
        ),
    ]
