# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_demo_dirname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_acy', models.CharField(max_length=32)),
                ('sts_sem', models.CharField(max_length=32)),
                ('std_serno', models.CharField(max_length=32)),
                ('cls_id', models.CharField(max_length=32)),
                ('sts_status', models.CharField(max_length=32)),
                ('sts_reason', models.CharField(max_length=32)),
                ('sts_ptpone', models.CharField(max_length=32)),
                ('sts_back', models.CharField(max_length=32)),
                ('sts_tsch', models.CharField(max_length=32)),
                ('sts_tdep', models.CharField(max_length=32)),
                ('sts_five', models.CharField(max_length=32)),
            ],
        ),
    ]
