# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_case_dep2_studsem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studsem',
            name='sts_reason',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
