# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20161203_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pef_key', models.IntegerField()),
                ('pef_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pefund_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pef_key', models.IntegerField()),
                ('pep_key', models.IntegerField()),
                ('dep_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Peplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pep_key', models.IntegerField()),
                ('pep_name', models.CharField(max_length=128)),
            ],
        ),
    ]
