# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20160418_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
