# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_pefund_pefund_rel_peplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pefund',
            name='pef_key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pefund_rel',
            name='pef_key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pefund_rel',
            name='pep_key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='peplan',
            name='pep_key',
            field=models.CharField(max_length=10),
        ),
    ]
