# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_work_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
