# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20160420_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
