# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20161208_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cas_no',
            field=models.CharField(max_length=64),
        ),
    ]
