# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_salary_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
