# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_studsem_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studsem_all',
            name='abg_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='abg_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='cls_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='col_fname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='dep_fname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='dep_no',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='eid_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='eid_code_a',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='eid_name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='eid_name2',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='eqa_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='eqa_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='esc_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='esc_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='hst_acy',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='hst_sem',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='hst_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='msg_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='prv_code_n',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='prv_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='sdp_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='sdp_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='sec_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='sub_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='sub_name2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='zip_name1',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studsem_all',
            name='zip_name2',
            field=models.CharField(max_length=16),
        ),
    ]
