# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 12:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20160501_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='type',
        ),
        migrations.AddField(
            model_name='salary',
            name='money',
            field=models.IntegerField(default=20000, validators=[django.core.validators.MaxValueValidator(80000), django.core.validators.MinValueValidator(20000)]),
        ),
    ]
