# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20160531_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
