# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_salary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
