# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Detail',
        ),
    ]
