# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160809_1136'),
        ('account', '0003_profile_adadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adAdmin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adAdmin2_fk', to='main.DBGroupName'),
        ),
        migrations.AddField(
            model_name='profile',
            name='atAdmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atAdmin_fk', to='main.DBGroupName'),
        ),
        migrations.AddField(
            model_name='profile',
            name='atAdmint2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atAdmint2_fk', to='main.DBGroupName'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adAdmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adAdmin_fk', to='main.DBGroupName'),
        ),
    ]
