# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160810_1132'),
        ('account', '0004_auto_20160810_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='atAdmint2',
        ),
        migrations.AddField(
            model_name='profile',
            name='atAdmin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atAdmin2_fk', to='main.DBGroupName'),
        ),
    ]
