# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_detail_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='code',
        ),
        migrations.AddField(
            model_name='detail',
            name='license',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
