# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160315_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 15, 12, 9, 1, 41852, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
