# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_detail_expire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Profile',
        ),
    ]
