# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160702_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groupQty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
