# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_groupqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groupQty',
        ),
    ]
