# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160727_1939'),
        ('account', '0010_profile_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.DBGroupName'),
            preserve_default=False,
        ),
    ]
