# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20160727_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isAuth',
            field=models.BooleanField(default=True),
        ),
    ]
