# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBGroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DBGroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('itemQty', models.IntegerField()),
                ('userQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('isActive', models.BooleanField(default=False)),
                ('appQty', models.IntegerField(default=0)),
                ('activeQty', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('isActive', models.BooleanField(default=False)),
                ('itemQty', models.IntegerField(default=0)),
                ('activeQty', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('isActive', models.BooleanField(default=False)),
                ('c1', models.CharField(blank=True, max_length=128)),
                ('c2', models.CharField(blank=True, max_length=128)),
                ('c3', models.CharField(blank=True, max_length=128)),
                ('c4', models.CharField(blank=True, max_length=128)),
                ('c5', models.CharField(blank=True, max_length=128)),
                ('c6', models.CharField(blank=True, max_length=128)),
                ('c7', models.CharField(blank=True, max_length=128)),
                ('c8', models.CharField(blank=True, max_length=128)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShinyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fileName', models.CharField(blank=True, max_length=64)),
                ('fileType', models.CharField(blank=True, max_length=64)),
                ('dirName', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Menu'),
        ),
        migrations.AddField(
            model_name='dbgroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DBGroupName'),
        ),
        migrations.AddField(
            model_name='dbgroupitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
