# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='dbgroupname',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='dbgroupname',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbgroupuser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DBGroupName'),
        ),
        migrations.AddField(
            model_name='dbgroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
