# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160809_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbgroupname',
            old_name='type',
            new_name='level',
        ),
    ]
