# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160315_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shinyapp',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
