# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160317_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='manu',
            new_name='menu',
        ),
    ]
