# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160809_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgroupname',
            name='itemQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dbgroupname',
            name='userQty',
            field=models.IntegerField(default=0),
        ),
    ]
