# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160317_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
