# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160322_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='appQty',
            field=models.IntegerField(default=0),
        ),
    ]
