# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_appqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='itemQty',
            field=models.IntegerField(default=0),
        ),
    ]
