# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menu_itemqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='activeQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='itemActiveQty',
            field=models.IntegerField(default=0),
        ),
    ]
