# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160415_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='shinyapp',
            name='fileName',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shinyapp',
            name='dirName',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shinyapp',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
