# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160416_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='shinyapp',
            name='fileType',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='shinyapp',
            name='fileName',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
