# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160416_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
