# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160419_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='itemActiveQty',
            new_name='activeQty',
        ),
    ]
