# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160604_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='shinyapp',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 13, 18, 0, 56, 846861, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
