# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_itemgroupname_itemgroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemGroupName',
            new_name='DBItemGroupName',
        ),
        migrations.RenameModel(
            old_name='ItemGroups',
            new_name='DBItemGroups',
        ),
    ]
