# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160701_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='permission',
        ),
    ]
