# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160704_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBGroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='DBItemGroupName',
            new_name='DBGroupName',
        ),
        migrations.RemoveField(
            model_name='dbitemgroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='dbitemgroups',
            name='item',
        ),
        migrations.RemoveField(
            model_name='dbitemgroups',
            name='user',
        ),
        migrations.DeleteModel(
            name='DBItemGroups',
        ),
        migrations.AddField(
            model_name='dbgroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DBGroupName'),
        ),
        migrations.AddField(
            model_name='dbgroupitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
